version: "3"

services:
    eap_router:
        build: ./router
        ports:
          - 8888:8000
        environment:
          - FE_SERVER=eap-frontend:8080
          - BE_SERVER=eap-backend:8081

    eap-frontend:
        build: ./frontend
        ports:
            - 8080:8080
        environment:
            - VUE_APP_API_URL=/api
  
    eap-backend:
        build: ./backend
        ports:
            - 8081:8081
        environment:
          - SNOWFLAKE_ACCOUNT=${SNOWFLAKE_ACCOUNT}
          - SNOWFLAKE_USER=${SNOWFLAKE_USER}
          - SNOWFLAKE_PASSWORD=${SNOWFLAKE_PASSWORD}
          - SNOWFLAKE_WAREHOUSE=${SNOWFLAKE_WAREHOUSE}
          - SNOWFLAKE_DATABASE=${SNOWFLAKE_DATABASE}
          - SNOWFLAKE_SCHEMA=${SNOWFLAKE_SCHEMA}
